# Verify the documentation coverage of this project by
#      `pip install docstr-coverage==2.2.0`
#      and then running `docstr-coverage` in the root of this repo.

paths:
  - huggingface/fashion_mnist_corrupted.py
  - additional_corruptions.py
  - create_png_examples.py
  - postprocess.py
  # Excluding mnist-c.py, as it is not our file, but simply taken from the mnist-c repo.
verbose: 3 # int (0-3)
skip_magic: True
skip_file_doc: False
skip_init: True
skip_class_def: False
skip_private: True
follow_links: True
percentage_only: False
fail_under: 100
